version: '3'

services:
  golang:
    build: 
      context: ./golang
      dockerfile: Dockerfile.code
    container_name: golang
    networks:
      - go-network
    tty: true
networks:
  go-network:
    driver: bridge